#!/bin/bash
echo "=== TimeTable Pro - Backend Setup ==="
echo ""
echo "1. Install dependencies:"
echo "   pip install -r requirements.txt"
echo ""
echo "2. Configure MySQL in timetable_backend/settings.py"
echo "   Update: NAME, USER, PASSWORD, HOST, PORT"
echo ""
echo "3. Create MySQL database:"
echo "   mysql -u root -p"
echo "   > CREATE DATABASE timetable_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
echo "   > EXIT;"
echo ""
echo "4. Run migrations:"
echo "   python manage.py migrate"
echo ""
echo "5. Seed demo data:"
echo "   python manage.py seed_data"
echo ""
echo "6. Start server:"
echo "   python manage.py runserver"
